// src/components/Badge/Badge.tsx
import React from "react";
import { type Variant, badgeVariants } from "./index";
import clsx from "clsx";

interface Props extends React.HTMLAttributes<HTMLElement> {
  href?: string;
  variant?: Variant;
  className?: string;
  children: React.ReactNode;
}

export default function Badge({
  href,
  variant = "default",
  className,
  children,
  ...rest
}: Props) {
  const Component = href ? "a" : "span";

  return (
    <Component
      href={href}
      className={clsx(badgeVariants({ variant, className }))}
      {...rest}
    >
      {children}
    </Component>
  );
}

// src/components/Badge/Badge.svelte
<script lang="ts">
  import { type Variant, badgeVariants } from "./index.js";
  import clsx from "clsx";

  let className: string | undefined | null = undefined;
  export let href: string | undefined = undefined;
  export let variant: Variant = "default";
  export { className as class };
</script>

<svelte:element
  this={href ? "a" : "span"}
  {href}
  class={clsx(badgeVariants({ variant, className }))}
  {...$$restProps}
>
  <slot />
</svelte:element>
