// src/components/Badge/badge.tsx
import React, { forwardRef } from 'react';
import { type Variant, badgeVariants } from "./index";
import clsx from "clsx";

interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement | HTMLAnchorElement> {
  className?: string | null;
  href?: string;
  variant?: Variant;
}

const Badge = forwardRef<
  HTMLSpanElement | HTMLAnchorElement,
  BadgeProps
>(({ className, href, variant = "default", children, ...restProps }, ref) => {
  const isLink = !!href;

  const componentProps = {
    ref,
    className: clsx(badgeVariants({ variant, className })),
    ...restProps
  };

  if (isLink) {
    return (
      <a
        href={href}
        {...componentProps as React.AnchorHTMLAttributes<HTMLAnchorElement>}
      >
        {children}
      </a>
    );
  }

  return (
    <span
      {...componentProps as React.HTMLAttributes<HTMLSpanElement>}
    >
      {children}
    </span>
  );
});

Badge.displayName = "Badge";

export { Badge };

// src/components/Badge/Badge.svelte
<script lang="ts">
  import { type Variant, badgeVariants } from "./index.js";
  import clsx from "clsx";

  let className: string | undefined | null = undefined;
  export let href: string | undefined = undefined;
  export let variant: Variant = "default";
  export { className as class };
</script>

<svelte:element
  this={href ? "a" : "span"}
  {href}
  class={clsx(badgeVariants({ variant, className }))}
  {...$$restProps}
>
  <slot />
</svelte:element>
