// src/components/ProjectCard.tsx
import React from "react";
import Badge from "./Badge/Badge";
import "./ProjectCard.css";

interface LinkItem {
  icon: any;
  type: string;
  href: string;
}

interface Props {
  className?: string;
  title: string;
  href?: string;
  description: string;
  tags: readonly string[];
  link?: string;
  image?: string;
  video?: string;
  links?: LinkItem[];
}

export default function ProjectCard({
  className = "",
  title,
  href = "",
  description,
  tags,
  link = "",
  image = "",
  video = "",
  links = [],
}: Props) {
  return (
    <div className={`item h-full flex flex-col ${className}`}>
      <a
        href={href || "#"}
        className="block cursor-pointer aspect-square image row-span-1"
      >
        <div className="h-full flex items-center justify-center my-logo">
          <div className="my-logo-text">{title.slice(0, 1)}</div>
        </div>
      </a>
      {/* Card Header */}
      <div className="content px-2 flex flex-col row-span-1">
        <div>
          {/* Card Title */}
          <span className="title mt-1 mb-3 text-3xl">{title}</span>
          <span className="hidden font-sans text-xs underline print:visible">
            {link?.replace("https://", "").replace("www.", "").replace("/", "")}
          </span>
          <div className="mt-4 mb-4">
            <span className="description">{description}</span>
          </div>
        </div>
        {/* Card Content */}
        <div className="mt-auto flex flex-col">
          {tags && tags.length > 0 && (
            <div className="mt-2 mb-4 flex flex-wrap gap-1">
              {tags.map(tag => (
                <Badge key={tag}>{tag}</Badge>
              ))}
            </div>
          )}
        </div>
        {/* Card Footer */}
        <div className="grid grid-cols-2 gap-1">
          {links &&
            links.length > 0 &&
            links.map((linkItem, index) => (
              <a
                key={index}
                href={linkItem?.href}
                target="_blank"
                rel="noopener noreferrer"
                className="buttonSm"
              >
                {linkItem.type}
              </a>
            ))}
        </div>
      </div>
    </div>
  );
}

// src/components/ProjectCard.svelte
<script lang="ts">
  import { marked } from "marked";
  import Badge from "@/components/Badge/Badge.svelte";

  let _class = "";
  export { _class as class };
  export let title: string;
  export let href: string = "";
  export let description: string;
  export let dates: string;
  export let tags: readonly string[];
  export let link: string = "";
  export let image: string = "";
  export let video: string = "";
  export let links: { icon: any; type: string; href: string }[] = [];
</script>

<!-- Card -->
<div class="item h-full flex flex-col overflow-hidden">
  <a href={href || "#"} class="block cursor-pointer aspect-square image">
    {#if video}
      <video
        class="pointer-events-none mx-auto h-40 w-full object-cover object-top"
        src={video}
        autoplay
        loop
        muted
      ></video>
    {:else}
      <img
        class="w-full overflow-hidden object-cover object-top"
        src={image}
        alt={title}
      />
    {/if}
  </a>
  <!-- Card Header -->
  <div class="content px-2 flex flex-col col-start-7 col-end-12 row-span-1">
    <div class="">
      <!-- Card Title -->
      <span class="title mt-1 mb-3 text-3xl">{title}</span>
      <span class="hidden font-sans text-xs underline print:visible">
        {link?.replace("https://", "").replace("www.", "").replace("/", "")}
      </span>
      <div
        class="mt-4 mb-4"
      >
        <!-- {@html marked(description)} -->
         <span class="description">{description}</span>
      </div>
    </div>
    <!-- Card Content -->
    <div class="mt-auto flex flex-col">
      {#if tags && tags.length > 0}
        <div class="mt-2 flex flex-wrap gap-1">
          {#each tags as tag}
            <Badge>
              {tag}
            </Badge>
          {/each}
        </div>
      {/if}
    </div>
    <!-- Card Footer -->
    <div class="pb-2 flex items-center pt-2">
      {#if links && links.length > 0}
        <div class="flex flex-row flex-wrap items-start gap-1">
          {#each links as link}
            <a href={link?.href} target="_blank">
              <Badge
                class="flex gap-1 items-center justify-center"
              >
                <!-- {link.icon} -->
                <svelte:component
                  this={link.icon}
                  class="mb-px"
                  size={10}
                  strokeWidth={1.5}
                />
                {link.type}
              </Badge>
            </a>
          {/each}
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .item {
    display: grid;
    grid-template-columns: subgrid;
    grid-column: span 12;
    grid-template-rows: auto;
    position: relative;
    grid-gap: 20px;
    gap: 20px;
    /* --overlap: calc(3px + 0.3vw); */
    --overlap: 0px;
  }

  .image {
    position: relative;
    background: var(--artBackground);
    cursor: -webkit-grab;
    cursor: grab;
    grid-column: 1 / 7;
    grid-row: span 2;
  }

  .content:hover .title {
    background-image: linear-gradient(
      transparent var(--overlap),
      var(--highlightColor) var(--overlap)
    );
    color: var(--invertedTextColor);
  }

  .content:hover .description {
    background-image: linear-gradient(
      transparent calc(var(--overlap) * 0.5),
      var(--highlightColor) calc(var(--overlap) * 0.5)
    );
    color: var(--invertedTextColor);
  }

  .content:hover :global(.badge) {
    background: var(--highlightColor);
    color: var(--invertedTextColor);
    border-color: var(--invertedTextColor);
  }

  @media (max-width: 959px) {
    .item {
      grid-column: 1/-1;
    }

    .image {
      grid-column: 1/8;
    }

    .content {
      grid-column: 8/-2;
    }
  }

  @media (max-width: 759px) {
    .item {
      row-gap: 8px;
    }

    .image {
      grid-column: 1/-1;
      grid-row: 1;
    }

    .content {
      grid-column: 1/-1;
      grid-row: 2;
    }
  }
</style>
